name: Build & Test

on:
  push:
    paths-ignore:
    - 'website/**'
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - edited

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql root password: "root"
        mysql database: "space_test"
        mysql user: "root"
        mysql password: "root"

    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: Build
      run: |
        go clean -i ./app/space/...
        cd ./app/space; CGO_ENABLED=0 go build -v ./...

    - name: Test
      run: CGO_ENABLED=0 go test -v $$(go list ./...)
