name: Build & Test

on:
  push:
    paths-ignore:
    - 'website/**'
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - edited

jobs:

  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql root password: "root"
        mysql database: "space_test"
        mysql user: "root"
        mysql password: "root"

    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Cache
      uses: actions/cache@v2.1.3
      with:
        path: ~/go/pkg/mod
        key: ${{ hashFiles('go.mod') }}

    - name: Get dependencies
      run: |
        go mod download

    - name: Build
      run: |
        go clean -i ./cmd/space/...
        cd ./cmd/space; go build -v ./...
        cd ./cmd/space; CGO_ENABLED=1 go build -tags=jsoniter -trimpath -ldflags '-s -w' ./...

    - name: Test
      run: go test -v ./...
